### ISSUE TITLE
user interface

### ISSUE THREAD

**Issue by theminted** [tricycle/lesswrong#532]
_From [mmein...@gmail.com](https://code.google.com/u/109934700508135265519/) on August 07, 2014 08:53:10_

What feature or behavior would you like to see?

Is there a directory I can search through by subject and find a 3D point plot of textbook name vs characteristics vs popularity that I can use? Tell us a story of a user using this feature (invent humorous character names):

_Original issue: http://code.google.com/p/lesswrong/issues/detail?id=435_

**Comment by matthewfallshaw** [comment]
No, sorry. There isn't.
