### ISSUE TITLE
Inability to comment or post anywhere except my own draft folder with user account "habryka"

### ISSUE THREAD

**Issue by theminted** [tricycle/lesswrong#542]
_From [panisne...@gmail.com](https://code.google.com/u/107296028352765495352/) on July 16, 2015 15:57:13_

What steps will reproduce the problem? 1. Log in to my user account ("habryka") 
2. Try to make a comment, or post a post anywhere but my own drafts folder
3. Get error message, or option simply not available What is the expected output? What do you see instead? I would expect to see the option to post my posts on main or discussion. I would also be able to comment on other people's posts and reply to other people's comments. What version of which web browser are you using? On what operating system? Chrome: Version 43.0.2357.134 (64-bit)
MacOs (Yosemite) Please provide any additional information below.

_Original issue: http://code.google.com/p/lesswrong/issues/detail?id=445_

**Comment by dshack** [comment]
I am also unable to comment anywhere with username "shack"

**Comment by wezm** [comment]
What is preventing you from commenting? Is there an error, lack of comment field? What post are you seeing this on?

**Comment by dshack** [comment]
There is no comment field available on any page.

**Comment by wezm** [comment]
@dshack,

You can't comment until you have verified your email address. If you didn't see an email from Less Wrong after signing up be sure to check your spam folder. If you don't find it, visit http://lesswrong.com/prefs/update/ and check that your email there is correct. If it isn't, update it and you'll be sent a new verification email. If it is correct then please email me (from the address in your profile) wes at trikeapps.com and I'll sort it out.

**Comment by dshack** [comment]
Aha, found the confusion. I got sent both a lesswrong wiki "confirm your email" message as well as one for the board. I clicked the wiki one, but not the other. Seems to work now. Thanks!
