### ISSUE TITLE
“REPORT ISSUES” in footer doesn't link to correct wiki page

### ISSUE THREAD

**Issue by malob** [tricycle/lesswrong#543]
Footer links to http://wiki.github.com/tricycle/lesswrong/issues-bugs-and-requested-features. Should like to https://github.com/tricycle/lesswrong/wiki/Issues,-Bugs,-and-Requested-Features

**Comment by craigsheen** [comment]
This is fixed by https://github.com/tricycle/lesswrong/pull/544. Should be deployed soon.
