### ISSUE TITLE
XSS in search page

### ISSUE THREAD

**Issue by m1el** [tricycle/lesswrong#545]
It is possible to execute arbitrary JavaScript code by providing specifically crafted url.

[http://lesswrong.com/search/results?q=%3C/script%3E%3Cscript%3Ealert(%271%22;%27)//](http://lesswrong.com/search/results?q=%3C/script%3E%3Cscript%3Ealert(%271%22;%27)//)

**Comment by wezm** [comment]
Thanks for letting us know.
