### ISSUE TITLE
Vagrantfile has obsolete version in box_url

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#546]
`  config.vm.box_url = "https://vagrantcloud.com/chef/boxes/ubuntu-12.04/versions/1.0.0/providers/virtualbox.box"`

Version 1.0.0 doesn't seem to exist anymore and gives a 404 error. 2.2.3 is the current version, but I haven't yet confirmed that it works with everything else.

**Comment by brendanlong** [comment]
The "chef" section is also redirecting to "bento". Notice that [this](https://vagrantcloud.com/chef) is empty, but if you go [here](https://atlas.hashicorp.com/chef/boxes/ubuntu-12.04) in the top left corner it says in the top left that it's actually bento/ubuntu-12.04.

12.04 is ancient at this point though, so I advise updating to 14.04..

**Comment by brendanlong** [comment]
Hm even using bento/ubuntu-12.04 version 2.2.3 causes something to go wrong in the Python setup.py. It might be a version thing..

**Comment by xrpd** [comment]
I used 

`config.vm.box_url = "https://vagrantcloud.com/bento/boxes/ubuntu-12.04/versions/2.2.3/providers/virtualbox.box"`

and got `vagrant up` to complete.

But 

`paster serve --reload development.ini`

failed with `ImportError: No module named _thread` (log [here](http://pastebin.com/LfiFU6s1)).  This seems to be something to do with easy_install eggs trying to use Python 3.

**Comment by brendanlong** [comment]
Hm, but `python` is Python 2.7:

    vagrant@vagrant:~$ python --version
    Python 2.7.3

**Comment by brendanlong** [comment]
It looks like `thread` was renamed to `_thread` in Python3 for some reason, and as a result of that, [the latest version of flup only supports Python 3](https://issues.mediagoblin.org/ticket/5373). A comment suggested using version 1.0.3.dev-20110405. I'm trying it now and I'll open a pull request if it works.

**Comment by xrpd** [comment]
There you go, it was just flup.  Dev environment up and running, thanks Brendan.

**Comment by harshhpareek** [comment]
Is this working for everyone? I'm still getting errors.

**Comment by brendanlong** [comment]
What errors?

**Comment by harshhpareek** [comment]
Never mind. it's working now
