### ISSUE TITLE
Linkposts not enabled

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#548]
The functionality to make link pages might still exist (see NewLink in pages.py as an example of a fragment), just not be used anywhere.

The link submit page should be available from a button below the 'create new article' button. (It can either be a separate page, or another tag on the submit page link it is in Reddit.) Link submissions should only be possible to Discussion.

**Comment by xrpd** [comment]
To confirm: when you look at http://lesswrong.com/r/discussion/ you'll see self texts (like now) and links mixed together in the same list.  

Also, link titles will link to the site (http://slatestarcodex.com/) as on reddit and not to lesswrong.com first.  To see comments you'll have to click on the Comments (0) link as on reddit.  Yes?

How should links and self texts be distinguished if at all? Some indication like "(externaldomain.com)" seems wise for links.  Do you want "[Link]" automatically added to the front of the title?  Do you want "(self.discussion)" or some such after self text posts?

Should link posts have an associated self text - effectively (but not technically) a "sticky" comment under the link?  Or should link posters be required to post a separate comment like everyone else?

**Comment by vaniver** [comment]
Yes, links and self posts mixed together. 
Yes, link goes through and comments are a separate link. 
Let's put [Link] in front of links. We should probably automatically strip [Link] (with any capitalization) from the start of the title in case the user adds it.
Lean against self texts. The OP can comment normally and I think the self text code has been modified to suit the needs for articles, making this harder than it needs to be.
