### ISSUE TITLE
Disable submission of articles to main

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#549]
This is a quick fix to force everything to Discussion while we work on a new way to organize content on LW. This is for regular users only; we should leave the ability for mods to submit and move posts to Main so they can still be Promoted.

**Comment by xrpd** [comment]
This patch is intended to resolve this issue ...

https://github.com/tricycle/lesswrong/pull/556

**Comment by xrpd** [comment]
Patch #556 not only prevents normal users from posting to main, but also prevents (normal user) article authors from _editing_ articles that have been previously posted to main, or that are subsequently posted to main by an admin or moderator.  

Is this acceptable?  (Admins and moderators can always edit.)

**Comment by vaniver** [comment]
Hmm. I'm leery of depriving people of the ability of editing their own articles. How much work do you think it would be to allow editing?

**Comment by xrpd** [comment]
@vaniver, I submitted a new pull request #557, which disables new posts to main, but allows editing of existing posts in main.  Please confirm with @wezm in the discussion in #556 that this is option you want.  The basic functionality of #556 is still available if you decide in the end that "locking" main to normal users is the better option for some reason.

**Comment by cdaloisio** [comment]
Merged #557
