### ISSUE TITLE
Require 10 karma to vote up or down

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#550]
This is supposed to be temporary measure because it's not great UX. (Ideally we should let them vote and record it but not count it until they're at 10 karma, but that'll probably wait until karma weighting is implemented.)

**Comment by harshhpareek** [comment]
There needs to be a mechanism for people to raise their karma quickly, and it should not incentivize low quality comments. If there is no such mechanism, this can feel a little strangling. Perhaps just karma requirement for downvotes is reasonable.

Currently, downvoting is rare on LW. You get 1 karma per post when no one downvotes, i.e. nothing you say is objectionable, though it may be low quality. I think having a place for discussion which gives easy karma  is also good to get people involved. I am creating another issue to discuss newbie threads, which could solve this issue

**Comment by xrpd** [comment]
I submitted pull request #558 to resolve this issue.  Nothing fancy.  You don't see voting icons until your karma reaches the 'no_voting_threshold' (a new configuration file parameter).  It uses the same method used to stop authors upvoting their own articles and comments.

**Comment by cdaloisio** [comment]
Merged #558
