### ISSUE TITLE
My like/dislike buttons are not appearing

### ISSUE THREAD

**Issue by act65** [tricycle/lesswrong#560]
The like and dislike buttons used to work fine, but now they dont (maybe a few weeks ago it stopped working). I dont know if you guys have changed anything? I dont think I have, so no idea what the problem is...

**Comment by wezm** [comment]
What is your username on LW?

**Comment by act65** [comment]
hey, sorry for the late reply.

act65

**Comment by cebuana83** [comment]
Hi Wezm, I have the same trouble with act65.

**Comment by jaischeema** [comment]
We are looking into this and will update you soon.

**Comment by vaniver** [comment]
act65 has 0 karma, so would be blocked from voting by #550 which requires 10 karma to vote up or down. (I'd start by posting something in the [welcome thread](http://lesswrong.com/lw/mij/welcome_to_less_wrong_8th_thread_july_2015/).)

**Comment by matthewfallshaw** [comment]
Feedback on hover over disabled voting buttons should resolve any confusion here. Something like "Voting disabled until you earn some more Karma. More information [on the wiki](#).".

**Comment by e1red** [comment]
Also note: Accounts that have not been through email verification cannot see the buttons.

This issue should be closed.
