### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by Houshalter** [tricycle/lesswrong#564]
Recently something changed with the lesswrong API. Attempting to open http://lesswrong.com/r/discussion/.json just gives an error, as does every other api request.

Also, the error page says to submit issues to https://code.google.com/archive/p/lesswrong/issues , but there is no way to submit an issue there.

**Comment by cdaloisio** [comment]
Thanks for reporting this issue @Houshalter. 😄 We've looked at the issue and deployed a fix.
