### ISSUE TITLE
Accounts have equal voting power

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#568]
Right now, all accounts count for the same amount of karma (1) when they vote. This should be replaced with a non-negative account variable, called "weight" or something similar, which is adjustable from the user page by anyone logged in as admin.

1. I suspect that a basic solution for the change to voting dynamics just necessitates changing line 85 of [this file](https://github.com/tricycle/lesswrong/blob/master/r2/r2/models/vote.py).

2. It's not as clear to me how to create the UI element to adjust the weight on the userpage, but it should be place by the other buttons that are only visible to admins.

Further **optional** elements:

3. Make the weight visible to everyone on the userpage, in a similar fashion to the total karma and karma over last 30 days bubbles.

4. Make new accounts start with a weight of 0, which increases to 1 at 10 karma. (This will allow us to revert #550 and close #560.)

This issue is *just* for changing new vote values. It seems likely that changing old votes will require a batch job, which will get put in a separate issue.

**Comment by matthewfallshaw** [comment]
If new users start with 0 weight we should ideally show them that on mouseover.
If it doesn't overly complicate the code I'd love to do something like enable upvoting at 10 karma and downvoting at 100 karma.
