### ISSUE TITLE
Meetup posting broken

### ISSUE THREAD

**Issue by rocurley** [tricycle/lesswrong#587]
Submitting a meetup appears to do nothing (that is to say, pressing the submit button does not load a new page). Despite this, a meetup post is in some sense created: every press of the submit button creates a new entry on the Upcoming Meetups page (to my chagrin). Attempting to open these meetups yields an error (for example [see](http://lesswrong.com/meetups/1r3)):

```
Error encountered

You have encountered an error in the code that runs Less Wrong. The site maintainers have been informed and will get to it is as soon as they can.

In the unlikely event that you've bumped into this error before and think that no-one is paying attention, please report the error and how to reproduce it on http://code.google.com/p/lesswrong/issues/list'

If the error is localised you might still find awesome Less Wrong content in the Main article area or in the Discussion area.
```

**Comment by jglamine** [comment]
Thanks for the bug report!

I've opened a PR with a fix.

**Comment by wezm** [comment]
Fix deployed.
