### ISSUE TITLE
Discussion is not working, and returning an error

### ISSUE THREAD

**Issue by avturchin** [tricycle/lesswrong#589]
Discussion is not working, and returning an error:
here: http://lesswrong.com/r/discussion/new/

"You have encountered an error in the code that runs Less Wrong. The site maintainers have been informed and will get to it is as soon as they can.

In the unlikely event that you've bumped into this error before and think that no-one is paying attention, please report the error and how to reproduce it on http://code.google.com/p/lesswrong/issues/list'

If the error is localised you might still find awesome Less Wrong content in the Main article area or in the Discussion area."

**Comment by alexpear** [comment]
I and a friend see the same problem today.

**Comment by wezm** [comment]
http://lesswrong.com/r/discussion/new/ is working again.

**Comment by alexpear** [comment]
Thanks for fixing that!
