### ISSUE TITLE
[Development] Paster hangs when running locally

### ISSUE THREAD

**Issue by alexpear** [tricycle/lesswrong#596]
I and at least one other person (Satvik) encountered a difficulty where, when running a local build, the paster serve call gets to the 'WSGIServer starting up' step, then gets no further. 

Satvik was able to fix this when they started again from a fresh clone, but that does not fix it for me. 

This is on a case-sensitive disk image on OSX.

**Comment by jack-trikeapps** [comment]
Just checking:
The development server doesn't print anything after "WSGIServer starting up" unless you make a request. I checked out a fresh copy of the git repo, ran `git submodule update --init` and then `vagrant provision`. Then with an entry for `lesswrong.local` in my `/etc/hosts`, I was able to point a browser to `lesswrong.local:8080` and it worked.

**Comment by alexpear** [comment]
Resolved: I was just being a little foolish and didn't realize that paster _was_ done, and it was waiting for me. Hitting 127.0.0.1:<port> with my browser brought up the 'It Works!' page.
